import type {
  LocalizationEngineLanguageCatalog,
  LocalizationLanguageCatalogEntry,
} from "./localization-contract";

const GOOGLE_GTX_LANGUAGES: readonly LocalizationLanguageCatalogEntry[] = [
  { code: "ar", label: "Arabic" },
  { code: "bn", label: "Bengali" },
  { code: "bg", label: "Bulgarian" },
  { code: "ca", label: "Catalan" },
  { code: "zh-CN", label: "Chinese (Simplified)" },
  { code: "hr", label: "Croatian" },
  { code: "cs", label: "Czech" },
  { code: "da", label: "Danish" },
  { code: "nl", label: "Dutch" },
  { code: "en", label: "English" },
  { code: "et", label: "Estonian" },
  { code: "fi", label: "Finnish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "el", label: "Greek" },
  { code: "gu", label: "Gujarati" },
  { code: "he", label: "Hebrew" },
  { code: "hi", label: "Hindi" },
  { code: "hu", label: "Hungarian" },
  { code: "is", label: "Icelandic" },
  { code: "id", label: "Indonesian" },
  { code: "it", label: "Italian" },
  { code: "ja", label: "Japanese" },
  { code: "kn", label: "Kannada" },
  { code: "ko", label: "Korean" },
  { code: "lv", label: "Latvian" },
  { code: "lt", label: "Lithuanian" },
  { code: "ml", label: "Malayalam" },
  { code: "mr", label: "Marathi" },
  { code: "no", label: "Norwegian" },
  { code: "fa", label: "Persian" },
  { code: "pl", label: "Polish" },
  { code: "pt", label: "Portuguese" },
  { code: "pa", label: "Punjabi" },
  { code: "ro", label: "Romanian" },
  { code: "ru", label: "Russian" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovenian" },
  { code: "es", label: "Spanish" },
  { code: "sw", label: "Swahili" },
  { code: "sv", label: "Swedish" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "th", label: "Thai" },
  { code: "tr", label: "Turkish" },
  { code: "uk", label: "Ukrainian" },
  { code: "ur", label: "Urdu" },
  { code: "vi", label: "Vietnamese" },
  { code: "zu", label: "Zulu" },
];

const APPLE_NATIVE_LANGUAGES: readonly LocalizationLanguageCatalogEntry[] = [
  { code: "ar-AE", label: "Arabic (United Arab Emirates)" },
  { code: "de", label: "German" },
  { code: "en", label: "English" },
  { code: "en-GB", label: "English (United Kingdom)" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "hi", label: "Hindi" },
  { code: "id", label: "Indonesian" },
  { code: "it", label: "Italian" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "nl", label: "Dutch" },
  { code: "pl", label: "Polish" },
  { code: "pt", label: "Portuguese" },
  { code: "ru", label: "Russian" },
  { code: "th", label: "Thai" },
  { code: "tr", label: "Turkish" },
  { code: "uk", label: "Ukrainian" },
  { code: "vi", label: "Vietnamese" },
  { code: "zh", label: "Chinese (Simplified)" },
  { code: "zh-TW", label: "Chinese (Traditional)" },
];

export const DEFAULT_ENGINE_LANGUAGE_CATALOGS: readonly LocalizationEngineLanguageCatalog[] =
  [
    {
      engineId: "apple-native",
      languages: APPLE_NATIVE_LANGUAGES,
    },
    {
      engineId: "google-gtx",
      languages: GOOGLE_GTX_LANGUAGES,
    },
    {
      engineId: "codex-gpt-5.4-mini",
      languages: GOOGLE_GTX_LANGUAGES,
    },
    {
      engineId: "codex-gpt-5.3-codex-spark",
      languages: GOOGLE_GTX_LANGUAGES,
    },
    {
      engineId: "anthropic-claude-haiku-4-5",
      languages: GOOGLE_GTX_LANGUAGES,
    },
    {
      engineId: "google/gemini-2.5-flash-lite",
      languages: GOOGLE_GTX_LANGUAGES,
    },
  ];
