export const buildDiagramModulesInlineContractBlock = (): string =>
  [
    "Diagram Modules inline format contract:",
    "- Core provides this contract inline; do not search for template files before writing staged Diagram Modules artifacts.",
    "- Use the examples below as the canonical Markdown shape for `product-parts.index.md` and `product-parts/<part-id>.md`.",
    "",
    "### `product-parts.index.md` minimal valid shape",
    "````markdown",
    "# Product Parts Index",
    "",
    "## Product Parts",
    "",
    "### Product Part: example-local-runtime",
    "- Id: example-local-runtime",
    "- Title: Local Runtime",
    "- Purpose: Runs local orchestration and workspace processing.",
    "- Status: generated",
    "````",
    "",
    "### `product-parts/<part-id>.md` minimal valid shape",
    "````markdown",
    "# Product Part: Local Runtime",
    "",
    "## Identity",
    "",
    "| Field | Value |",
    "| ----- | ----- |",
    "| Part ID | `example-local-runtime` |",
    "| Product Part | `Local Runtime` |",
    "| Purpose | Runs local orchestration and workspace processing. |",
    "",
    "## Purpose",
    "",
    "Runs the main orchestration and workspace processing logic.",
    "",
    "## Owned Clusters",
    "",
    "### `runtime-orchestration`",
    "",
    "**Purpose:** Coordinates staged workflow execution.",
    "",
    "| `module-id` | Responsibility |",
    "| --- | --- |",
    "| `workflow-step-runner` | Executes the active workflow step. |",
    "",
    "## Standalone Modules",
    "",
    "| `module-id` | Responsibility |",
    "| --- | --- |",
    "| `provider-session-bridge` | Connects provider turns with runtime sessions. |",
    "",
    "## Simple Relations",
    "",
    "| From | To | Type | Label |",
    "| --- | --- | --- | --- |",
    "| `workflow-step-runner` | `provider-session-bridge` | async-event | workflow-state-snapshot |",
    "",
    "## Assumptions / Open Questions",
    "",
    "- Relations are optional and should stay sparse.",
    "````",
    "",
    "Canonical validation reminders:",
    "- Product Part ids and module ids are lowercase kebab-case.",
    "- The index title must be exactly `# Product Parts Index`.",
    "- Every index entry uses `### Product Part: <part-id>` plus `Id`, `Title`, `Purpose`, and `Status` fields.",
    "- Every Product Part file title starts with `# Product Part:` and includes an Identity table with `Part ID` matching its file name.",
    "- Cluster headings use `### `cluster-id`` and module rows use ``| `module-id` | Responsibility |``.",
    "- Keep Product Part / Cluster / Module names and ids in canonical English; localize only descriptive prose.",
  ].join("\n");
